services:
  cross-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: >
      -c "mkdir -p build-arm64 && 
          cd build-arm64 && 
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchain-arm64.cmake -DCURL_INCLUDE_DIR=/usr/include/aarch64-linux-gnu -DCURL_LIBRARY=/usr/lib/aarch64-linux-gnu/libcurl.so && 
          make -j"
  
  cross-shell:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: -c "/bin/bash"
    stdin_open: true
    tty: true